// <auto-generated />
namespace CustomerSatisfaction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ini2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ini2));
        
        string IMigrationMetadata.Id
        {
            get { return "201607181936401_Ini2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
